package biz.coolpage.hcs.mixin.loot;

import com.llamalad7.mixinextras.injector.ModifyReturnValue;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.LootTable;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;

// The removeIf function of the Forge API WheatSeedDropModifier is not working, don't know why
@Mixin(LootTable.class)
public class WheatSeedDropModifierMixin {
    // Intercept the return result of the loot list using MixinExtras' @ModifyReturnValue
    @Contract("_, _ -> param1")
    @ModifyReturnValue(
            method = "getRandomItems(Lnet/minecraft/world/level/storage/loot/LootContext;)Lit/unimi/dsi/fastutil/objects/ObjectArrayList;",
            at = @At("RETURN")
    )
    private @NotNull ObjectArrayList<ItemStack> hcsurvival$modifyWheatSeedDrops(@NotNull ObjectArrayList<ItemStack> generatedLoot, LootContext context) {
        // Remove wheat seeds 95% of the time to achieve 1/20 of the original drop rate
        generatedLoot.removeIf(stack -> {
            if (stack.getItem() == Items.WHEAT_SEEDS) {
                // Determine whether to remove based on the rate
                // Only print the log when a wheat seed is ACTUALLY generated by vanilla loot table
                return context.getRandom().nextFloat() >= 0.08f;
            }
            return false;
        });

        return generatedLoot;
    }
}